### ISSUE TITLE
3.10 Breaks OpenAuth DNS

### ISSUE THREAD

**Issue by walln** [anomalyco/sst#5589]
Upgrading to 3.10 with the new router breaks OpenAuth when using custom DNS. The tokens will get issued with the `iss` field as the underlying lambda url instead of the provided DNS.

**Comment by vic-brev** [comment]
Thanks for filing this. This impacted us as well, and we had to downgrade to 3.9

**Comment by jayair** [comment]
Taking a look.

**Comment by fwang** [comment]
Can u give the latest v3.10.5 a try? This is likely fixed in v3.10.2.

**Comment by vic-brev** [comment]
v3.10.4 was not fixed when I tried a couple hours ago. I can try v3.10.5 a bit later but I'm happy with v3.9.44 for now.

**Comment by fwang** [comment]
Fixed in v3.10.8.

Feel free to reopen if issue persists.

**Comment by pinoniq** [comment]
just so others know. I had to remove my local stage since it wasn't updating the cloudfront distribution.

**Comment by pinoniq** [comment]
Not fixed. Adding a domain to sst.aws.Auth still has OpenAuthProviders use the lambda url instead of the cloudfront one in the redirect_uri

**Comment by pinoniq** [comment]
Pretty sure the issue stems from how the Router is created in the Auth component;

```
routes: {
  "/*": issuer.url,
},
```

Which then is transformed in normalizeRoutes to: `route = typeof route === "string" ? { url: route } : route;`

and so no "type" is set here. Meaning the fix https://github.com/sst/sst/commit/122348af02cb4f3b11ae4cebc7bbab9f27384ca5 here doesn't work given the type is not set.

**Comment by vic-brev** [comment]
confirming that 3.10.5 correctly sets the `iss` in the token to the specified domain.

**Comment by yazalulloa** [comment]
I have the same problem with adding domain to the Auth component, the redirect it gives to the oauth provider is the generated url instead of the custom domain, had to rollback to 3.9.44

**Comment by pinoniq** [comment]
Did some more digging. And it seems to actually be cased by the sst Auth component using the ´inlineRoutes´. This means no function is created that ads the header, and instead it just uses the recommended Origin request policy for lambda's which removes the host header.

**Comment by fwang** [comment]
Should be fixed in v3.10.10.

Just updated `Auth` to use the new lazy routes. Thanks for looking into this!

**Comment by pinoniq** [comment]
I believe there is also something wrong with those lazyroutes. given I had to specify the domainname. a simple / didnt work for me, CF would give 502's and not hit the lambda. Ill see if I can give you a reproduction tomorrow

**Comment by fwang** [comment]
> given I had to specify the domainname. a simple / didnt work for me

Can I see ur sst config code?

**Comment by pinoniq** [comment]
```
const authRouter = new sst.aws.Router("AuthRouter", {
            domain:
                $app.stage === "production"
                    ? "auth.REDACTED.tld"
                    : `auth.${$app.stage}.REDACTED.tld`,
        });

        const authStorage = new sst.aws.Dynamo("AuthStorage", {
            fields: { pk: "string", sk: "string" },
            primaryIndex: { hashKey: "pk", rangeKey: "sk" },
            ttl: "expiry",
        });

        const authIssuer = new sst.aws.Function("AuthIssuer", {
            handler: "auth/index.handler",
            link: [GoogleClientId, GoogleClientSecret, authStorage],
            url: true,
        });

        authRouter.route(
            "/", // <---- this doesn't work. CF is giving me 502's. if I add the domain from the Router, it does work.
            authIssuer.url,
        );
```

**Comment by pinoniq** [comment]
If I use the updated sst Auth component, I get the same 502 behavior. I did notice the / is stripped of at the end (.tld and not .tld/) and so this probably borks the .startsWith check in the CF Function

**Comment by fwang** [comment]
hmm I tried the `Auth` component and creating the issuer manually, both worked for me.

Here's my code for creating the issuer manually. For `sst.config.ts`:

```ts
const router = new sst.aws.Router("Router", {
  domain: "router.mydomain.com",
});

const storage = new sst.aws.Dynamo("AuthStorage", {
  fields: { pk: "string", sk: "string" },
  primaryIndex: { hashKey: "pk", rangeKey: "sk" },
  ttl: "expiry",
});

const issuer = new sst.aws.Function("AuthIssuer", {
  handler: "functions/auth/index.handler",
  link: [storage],
  url: true,
});

router.route("/", issuer.url);
```

And here's `index.ts`

```ts
import { Resource } from "sst";
import { authorizer } from "@openauthjs/openauth";
import { handle } from "hono/aws-lambda";
import { subjects } from "./subjects.js";
import { GoogleAdapter } from "@openauthjs/openauth/adapter/google";
import { DynamoStorage } from "@openauthjs/openauth/storage/dynamo";

const app = authorizer({
  subjects,
  storage: DynamoStorage({
    table: Resource.AuthStorage.name,
    pk: "pk",
    sk: "sk",
  }),
  providers: {
    google: GoogleAdapter({
      clientID: "MY_GOOGLE_CLIENT_ID",
      clientSecret: "MY_GOOGLE_CLIENT_SECRET",
      scopes: ["email"],
    }),
  },
  success: async (ctx, value) => {
    if (value.provider === "google") {
      return ctx.subject("user", {
        email: value.tokenset.access, // dummy code
      });
    }
    throw new Error("Invalid provider");
  },
});

// @ts-ignore
export const handler = handle(app);
```

And after I deployed, here are the steps i tested:
- On Google Cloud Console, set
  - Authorized JavaScript origins: `https://router.mydomain.com`
  - Authorized redirect URIs: `https://router.mydomain.com/google/callback`
- Go to https://router.mydomain.com/authorize?client_id=web&redirect_uri=http://router.mydomain.com&response_type=token
  <img width="591" alt="Image" src="https://github.com/user-attachments/assets/667ffd6b-50b4-415f-96b4-180792361701" />
- Click `Continue with Google` and login w/ my Google account
- Redirected back to `https://router.mydomain.com` with access token in the URL
  <img width="1099" alt="Image" src="https://github.com/user-attachments/assets/74df85db-6a41-4f05-a8de-906eef9a665f" />

**Comment by mwood23** [comment]
Upgraded to `3.10.11` and it resolved everything for me! Using the SST auth component. Thanks!

**Comment by yazalulloa** [comment]
Upgraded to 3.10.11 and it works with both google and github login, thanks

**Comment by fwang** [comment]
Closing for now. @pinoniq feel free to reopen if issue persist.
