### ISSUE TITLE
Tunnel not working after upgrade to 3.12.3

### ISSUE THREAD

**Issue by andrewcoelho** [anomalyco/sst#5657]
I updated from 3.9.4 to 3.12.3 which may or may not be related, but since then I can't get the tunnel to work.

```
// npx sst tunnel --stage production --print-logs

time=2025-04-03T09:46:47.644-04:00 level=INFO msg="checking for pulumi" path="/Users/andrew/Library/Application Support/sst/bin/pulumi"
time=2025-04-03T09:46:48.541-04:00 level=INFO msg="checking for bun" path="/Users/andrew/Library/Application Support/sst/bin/bun"
time=2025-04-03T09:46:49.155-04:00 level=INFO msg="starting tunnel"
time=2025-04-03T09:46:49.155-04:00 level=INFO msg="initializing project" version=3.12.3
time=2025-04-03T09:46:49.156-04:00 level=INFO msg="esbuild building" out=/Users/andrew/Projects/xxx/.sst/platform/sst.config.1743688009156.mjs
time=2025-04-03T09:46:49.166-04:00 level=INFO msg="esbuild built" outfile=/Users/andrew/Projects/xxx/.sst/platform/sst.config.1743688009156.mjs
time=2025-04-03T09:46:49.167-04:00 level=INFO msg="evaluating config"
time=2025-04-03T09:46:49.202-04:00 level=INFO msg="config evaluated"
time=2025-04-03T09:46:49.204-04:00 level=INFO msg="checking platform"
time=2025-04-03T09:46:49.205-04:00 level=INFO msg="checking provider" name=command version=1.0.2 compare=1.0.2
time=2025-04-03T09:46:49.205-04:00 level=INFO msg="loading home"
time=2025-04-03T09:46:50.007-04:00 level=INFO msg="aws credentials found" region=us-east-2 profile=xxx-prod
time=2025-04-03T09:46:50.007-04:00 level=INFO msg="fetching bootstrap"
time=2025-04-03T09:46:50.251-04:00 level=INFO msg="found existing bootstrap" data="{\"version\":5,\"asset\":\"sst-asset-xxx\",\"assetEcrRegistryId\":\"xxx\",\"assetEcrUrl\":\"xxx.dkr.ecr.us-east-2.amazonaws.com/sst-asset\",\"state\":\"sst-state-xxx\",\"appsyncHttp\":\"\",\"appsyncRealtime\":\"\"}"
time=2025-04-03T09:46:50.251-04:00 level=INFO msg="loaded config" app=xxx stage=production
time=2025-04-03T09:46:50.252-04:00 level=INFO msg="INFO getting passphrase app=xxx stage=production"
time=2025-04-03T09:46:50.432-04:00 level=INFO msg="INFO pulling state app=xxx stage=production out=/Users/andrew/Projects/xxx/.sst/pulumi/xxx/.pulumi/stacks/xxx/production.json"
time=2025-04-03T09:46:51.045-04:00 level=INFO msg="starting tunnel" cmd="[sudo -n -E /opt/sst/tunnel tunnel start --subnets 10.0.4.0/22,10.0.12.0/22,10.0.0.0/22,10.0.8.0/22 --host xxx --user ec2-user --print-logs]"
Tunnel

➜  Forwarding ranges
   10.0.4.0/22
   10.0.12.0/22
   10.0.0.0/22
   10.0.8.0/22

Waiting for connections...

time=2025-04-03T09:48:06.371-04:00 level=INFO msg="killing process" pid=2173
time=2025-04-03T09:48:06.372-04:00 level=INFO msg="killing process" pid=2173
time=2025-04-03T09:48:06.372-04:00 level=INFO msg="process killed with term" pid=2173
time=2025-04-03T09:48:06.372-04:00 level=INFO msg="untracked process" pid=2173
time=2025-04-03T09:48:06.372-04:00 level=ERROR msg="failed to send sigterm" pid=2173
```

As you can see the tunnel seemingly runs for about 2 minutes before the process is killed. During those 2 minutes, trying to connect to my database from `npx sst shell --stage production` and then `psql -h <hostname>` gives me a server closed connection error.

Trying to run tunnel again it exits immediately.

I've tried restarting my computer, tried multiple networks that are working fine, and no luck getting this to work.

additional logs from sst diagnostic:

```
time=2025-04-03T09:31:49.882-04:00 level=INFO msg="tunnel started"
time=2025-04-03T09:33:04.855-04:00 level=ERROR msg="failed to start tunnel" error="dial tcp xxx:22: connect: operation timed out"
time=2025-04-03T09:33:04.857-04:00 level=INFO msg="running command" command="[ifconfig utun69 destroy]"
time=2025-04-03T09:33:04.865-04:00 level=ERROR msg="failed to execute command" command="[ifconfig utun69 destroy]" 
```

Not sure if relevant, but for
```
sudo -n -E /opt/sst/tunnel tunnel start --subnets 10.0.4.0/22,10.0.12.0/22,10.0.0.0/22,10.0.8.0/22 --host x.x.x.x --user ec2-user --print-logs
```

the value printed after --host does not match any of the IP's for EC2 instances that I can see in the console. 

my sst.config.ts has
```
const vpc = new sst.aws.Vpc('Vpc', {
  bastion: true,
  nat: 'ec2',
});
```

ETA: I renamed my VPC and tried re-deploying. This failed, so I undid the rename on the VPC. This looks like it created some new EC2 instances in my account and the tunnel is now working and outputting an existing EC2 instance IP address after --host.

While the problem is resolved for now, I'm still curious to know why SST was trying to use the wrong IP value for --host after I upgraded to 3.12.3 and re-deployed.

**Comment by amineelmoussafer** [comment]
Same here !

**Comment by Liamandrew** [comment]
Glad I'm not the only one - this is quite an important issue to be addressed

**Comment by thdxr** [comment]
trying to recreate

**Comment by thdxr** [comment]
did any of you try an `sst refresh` when it wasn't working? i couldn't recreate this

**Comment by andrewcoelho** [comment]
Yeah I tried sst refresh a couple times with no luck.

**Comment by gmathieu** [comment]
I can confirm that the tunnel only works for **the personal stage**. I tried downgrading to previous versions, `3.11.21` and `3.9.4`, running `sst refresh`, without luck. Help would be greatly appreciated 🙏.

**Comment by gmathieu** [comment]
I found a workaround by tunneling to your personal stage. The trick is to deploy your personal stage that points to the same VPC used in the production stage.

Here's how to reproduce:
1. Grab the **production's VPC ID** (skip the sub-steps if you already know it):
    1. Update `sst.config.ts` to expose your production's VPC ID
    
        ```ts
        export default $config({
          // ...
          async run() {
            const vpc = new sst.aws.Vpc('vpc', { bastion: true,nat: 'ec2' })
            // ...
            return { vpcId: vpc.id }
          }
        }
        ```
    1. Output the VPD ID by running `sst refresh --stage production`
4. Update your `sst.config.ts` to reuse production's VPC
  
    ```ts
    export default $config({
      async run() {
        sst.aws.Vpc.get("vpc", "VPC's ID")
        // I recommend removing all other components since we don't want to deploy to production
      }
    }
    ```

6. Deploy your **personal stage**: `sst deploy`
7. Undo any changes to `sst.config.ts`
8. Tunnel using your **personal stage** `sst tunnel`
9. Run whatever you need on the production stage `sst shell --stage production ...`

Note: both the production stage and your personal must be deployed in the same AWS account.

**Comment by Thevetat** [comment]
Getting the same on a 3.12.3 build.

**Comment by Liamandrew** [comment]
This is fixed for me after upgrading to `3.12.6` 🎉

**Comment by ghardin1314** [comment]
Still running into this problem with `3.13.1`. I tried the workaround to tunnel on a personal stage and my connection gets tunneled but still seems to timeout without reaching the database. Eventually it did start working. I think there may be 2 issues here

1. The tunnel on production stage is not resolving the right IP (no idea why). Seems to work on any non production stage if you use VPC.get(...)
2. I think Aurora may just take a long time to spin up? This was a new stage for me in production and after about an hour or two the connection finally made it through and I could run my migrations

**Comment by ghardin1314** [comment]
I think I narrowed it down, at least for my case. The issue seems to be with reusing the `nat` ec2 instance for the bastion. When I remove the `nat` from the `vpc` and it redeploys a standalone bastion instance then the tunnel works fine. When I add back the `nat`, the tunnel seems to not resolve the right IP for either of the `nat` instances

![Image](https://github.com/user-attachments/assets/9069017f-97a3-4199-b4bf-95d6d542b932)

![Image](https://github.com/user-attachments/assets/1e6ef245-a051-4b5e-aca2-b1352af6f711)

**Comment by pauljasperdev** [comment]
> Not sure if relevant, but for
> 
> ```
> sudo -n -E /opt/sst/tunnel tunnel start --subnets 10.0.4.0/22,10.0.12.0/22,10.0.0.0/22,10.0.8.0/22 --host x.x.x.x --user ec2-user --print-logs
> ```
> 
> the value printed after --host does not match any of the IP's for EC2 instances that I can see in the console.

I've seen this too. Tunneling failed due to wrong IP.

I downgraded to `3.10.7` and tested with personal stage. Only after remove and redeploy the IP changed. Having a `3.12.3` deployment and tunneling with a `3.10.7` without redeploying shows the wrong IP.

EDIT:
Tried with `sst tunnel --stage mystage` instead of `sst dev` tunnel today. No luck. IP is wrong again. Tunneling to personal stage via just `sst tunnel` resolves a correct IP.

**Comment by natew** [comment]
I tried a *ton* of things - upgrading, downgrading, re-deploying, managed/nat, etc. None worked, then I restarted my Mac and it worked 🤷

**Comment by pauljaspersahr** [comment]
> > Not sure if relevant, but for
> > ```
> > sudo -n -E /opt/sst/tunnel tunnel start --subnets 10.0.4.0/22,10.0.12.0/22,10.0.0.0/22,10.0.8.0/22 --host x.x.x.x --user ec2-user --print-logs
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > the value printed after --host does not match any of the IP's for EC2 instances that I can see in the console.
> 
> I've seen this too. Tunneling failed due to wrong IP.
> 
> I downgraded to `3.10.7` and tested with personal stage. Only after remove and redeploy the IP changed. Having a `3.12.3` deployment and tunneling with a `3.10.7` without redeploying shows the wrong IP.
> 
> EDIT: Tried with `sst tunnel --stage mystage` instead of `sst dev` tunnel today. No luck. IP is wrong again. Tunneling to personal stage via just `sst tunnel` resolves a correct IP.

**Comment by pauljasperdev** [comment]
> I think I narrowed it down, at least for my case. The issue seems to be with reusing the `nat` ec2 instance for the bastion. When I remove the `nat` from the `vpc` and it redeploys a standalone bastion instance then the tunnel works fine. When I add back the `nat`, the tunnel seems to not resolve the right IP for either of the `nat` instances
> 
> ![Image](https://github.com/user-attachments/assets/9069017f-97a3-4199-b4bf-95d6d542b932)
> 
> ![Image](https://github.com/user-attachments/assets/1e6ef245-a051-4b5e-aca2-b1352af6f711)

This worked for me for production stage.

```typescript
export const vpc = new sst.aws.Vpc('MyVpc', {
  bastion: true,
  nat: 'managed',
  // nat: 'ec2',
});
```

Changing to `nat: 'managed'` redeployed a bastion host and I could tunnel to it. After appling schema changes I swiched back.

**Comment by ghardin1314** [comment]
> I tried a _ton_ of things - upgrading, downgrading, re-deploying, managed/nat, etc. None worked, then I restarted my Mac and it worked 🤷

I also just restarted my Mac and it seems to be working correctly with `nat: 'ec2'`. Weird

Edit: I spoke to soon. Working fine on my dev stage but not on production

**Comment by thdxr** [comment]
we have an issue that i'm working on a fix for - some of your issues is caused by hanging `.server` files in the `.sst` folder

if you delete those it may start to work

**Comment by partmor** [comment]
> we have an issue that i'm working on a fix for - some of your issues is caused by hanging `.server` files in the `.sst` folder
> 
> if you delete those it may start to work

@thdxr I am experiencing the same issues and don't even have `.server` files in the `.sst` folder bc I did:

```
rm -rf .sst
sst install
sst tunnel --stage=myStage --print-logs
```

the printed logs consistently show an attempt to connect to the wrong IP (locally, in CI, ...).
it only gets the right IP for personal stage

given that this happens to me also in a CI linux machine (and checked the wrong IPs are consistent...), i doubt it has to specifically with macos

**Comment by n-batalha** [comment]
To temporarily resolve this, I deleted the `.sst` folder and recreated it. It solved the tunneling issue but now my next app deployment via `sst deploy` is failing. I assume it's related (I didn't had it before and no other change made) but I don't understand it yet

```
   Generating static pages (12/17) 
Error occurred prerendering page "/app/photos". Read more: https://nextjs.org/docs/messages/prerender-error
Error: write CONNECT_TIMEOUT REDACTEDHOSTNAMEOFDB.proxy-cpo4km0kq4nv.eu-west-1.rds.amazonaws.com:5432
```

**Comment by fvaldes33** [comment]
Can confirm it works when I switch over to a manage nat instance for my vpc. Switching back to ec2 breaks it again

**Comment by bigbyte-dom** [comment]
Can also confirm switching to managed nat sorted this out (after cleaning up a few failed elastic IP attachment issues from the switch)

**Comment by n-batalha** [comment]
On `"sst": "3.13.9"` (on a mac). The removal of `.sst` worked yesterday but weirdly not today, the change to `nat: 'managed'` does work as others said. The IP in the sst tunnel logs with `nat: 'ec2'` doesn't match any EC2 instance public IP.

In the mix, random immediate exits/crashes of `sst tunnel` like in https://github.com/sst/sst/issues/5008, nothing useful in `--print-logs` though.

**Comment by thdxr** [comment]
@partmor can you do `sst state export --stage=mystage` and see if the old IP is in the state file somewhere?

**Comment by ghardin1314** [comment]
@thdxr I can confirm the old IP that tunnel is trying to connect to is in the state file still. Seems to be a leftover resource because the actual ec2 nats are also present in the state file. Can send it if that would be helpful

Also any ETA on the fix landing? This is really hanging up our ability to get a few things out the door

**Comment by amineelmoussafer** [comment]
To be able to access the tunnel, I managed to connect by following these steps:
	1.	Remove the .server files in the .sst folder.
	2.	In your sst.config, add the following line:
                          sst.aws.Vpc.get('vpc', 'your-vpc-id');
	3.	Just Run the development environment with:
                         npx sst dev

With this setup, there’s no need to deploy to different stages while waiting for a fix for this issue.

**Comment by jeremyhicks** [comment]
I'm using sst version 3.13.10 this is still an issue, and when the tunnel is running I'm not able to access the resources such as RDS DB

**Comment by jb-chief** [comment]
fwiw, i was able to fix this today by doing `npx sst deploy --stage production --target MyVpcName`. after running that, the IPs started matching up properly.

**Comment by jeremyhicks** [comment]
Thanks, that didn't work for me. The tunnel will still disconnect. I'm trying to connect to the production database. When the tunnel is running I get this message
```
connection to server at "10.0.15.185", port 5432 failed: server closed the connection unexpectedly
This probably means the server terminated abnormally
before or while processing the request
```

**Comment by mwood23** [comment]
Deleting the `.sst` folder and moving to managed fix it for me. Still an issue on `3.13.14`. This was how I got it to finally work:

```ts
export const vpc = new sst.aws.Vpc('Vpc', { bastion: true, nat: 'managed' });
```

First, I flipped nat from `ec2` to `managed` and got some errors about resource conflicts. Then I named it to `Vpc2` and that made more errors like: `The new Subnets are not in the same Vpc as the existing subnet group`. Then I renamed it back to `Vpc` and it worked worked itself out 🤷.

Another interesting change around this in the past few months is that I have to run `sst tunnel` separately from my dev process. I remember that I didn't need to do that at one time.

**Comment by AlessandroVol23** [comment]
I had the same issue (only on a deployed stage on prod not on dev while running sst)

I try to do it like that:
- Start `sst tunnel --stage prod --print-logs`
- Start drizzle studio

On Drizzle Studio I get a `ECONNRESET` and I don't see any IPs forwarded

![Image](https://github.com/user-attachments/assets/f77f8d93-e40e-4155-8108-5ed44f1d4ea5)


After some time the tunnel was killed:

```
time=2025-04-25T07:24:23.461+02:00 level=INFO msg="killing process" pid=35807
time=2025-04-25T07:24:23.462+02:00 level=INFO msg="process killed with term" pid=35807
time=2025-04-25T07:24:23.462+02:00 level=INFO msg="untracked process" pid=35807
time=2025-04-25T07:24:23.462+02:00 level=INFO msg="killing process" pid=35807
time=2025-04-25T07:24:23.462+02:00 level=ERROR msg="failed to send sigterm" pid=35807
```

Tried the following until it worked:
1. Remove `.server` files -> **no available in `.sst`** 
2. Remove `.sst` folder and do `sst install`-> **Same issue**
3. Upgraded from 3.13.14 to 3.13.18 -> **Same issue**
4. Changing my VPC from `{ bastion: true, nat: 'ec2' }` to `{ bastion: true, nat: 'ec2' }` to ` new sst.aws.Vpc('MyVpc', { bastion: false })` to remove EC2 and add it back again -> **Same Issue**
5. Changing VPC Bastion from `ec2` to `managed` -> **Error while deploying** ` waiting for EC2 NAT Gateway (nat-076890c52b4b5a002) create: unexpected state 'failed', wanted target 'available'. last error: Resource.AlreadyAssociated: Elastic IP address [eipalloc-07ba5cda18b230d4c] is already associated: provider=aws@6.66.2` -> **WORKS**

After step 5 it worked. But I don't want to be in this weird state of wanting to deploy a managed nat gateway (which is too expensive for this case anyway) + facing a deployment error. So I try going back to EC2

6. Changing it back to `ec2` -> **Same error as before**
7. Renaming VPC from `MyVpc` to `MyVpc2` -> **Error while deploying** ` operation error RDS: ModifyDBSubnetGroup, https response error StatusCode: 400, RequestID: ada5ea40-1b4a-4381-8cf4-eb9f84ac8f11, api error InvalidParameterValue: The new Subnets are not in the same Vpc as the existing subnet group: provider=aws@6.66.2`
8. Going back to original name of VPC -> same error
9. `sst refresh --stage prod` -> Maybe its updating the IPs? Not sure where they are in the state exactly -> Now the tunnel is immediately failing 

``` 
time=2025-04-25T07:44:21.718+02:00 level=INFO msg="starting tunnel" cmd="[sudo -n -E /opt/sst/tunnel tunnel start --subnets 10.0.4.0/22,10.0.12.0/22,10.0.0.0/22,10.0.8.0/22 --host 3.122.53.251 --user ec2-user --print-logs]"
Tunnel

➜  Forwarding ranges
   10.0.4.0/22
   10.0.12.0/22
   10.0.0.0/22
   10.0.8.0/22

Waiting for connections...

time=2025-04-25T07:44:21.814+02:00 level=INFO msg="killing process" pid=41189
time=2025-04-25T07:44:21.814+02:00 level=INFO msg="killing process" pid=41189
time=2025-04-25T07:44:21.814+02:00 level=ERROR msg="failed to send sigterm" pid=41189
time=2025-04-25T07:44:21.814+02:00 level=INFO msg="process killed with term" pid=41189
time=2025-04-25T07:44:21.814+02:00 level=INFO msg="untracked process" pid=41189
```

10. Deployed prod again **And it works**

So maybe it was just a thing of 
- updating SST
- refreshing the state
- deploying again

I probably triggered something somehow to update the IPs it should connect to. But now it looks fine (at the moment).

Maybe that helps somebody

**Comment by jeremyhicks** [comment]
> 9. `sst refresh --stage prod` -> Maybe its updating the IPs? Not sure where they are in the state exactly -> Now the tunnel is immediately failing
> 10. Deployed prod again **And it works**
> 
> So maybe it was just a thing of
> 
> * updating SST
> * refreshing the state
> * deploying again
> 
> I probably triggered something somehow to update the IPs it should connect to. But now it looks fine (at the moment).
> 
> Maybe that helps somebody

Thank you for the detailed steps, I had done them all but it was #9 and #10 that finally did the trick for me

**Comment by CameronScully** [comment]
Works for prod but not for dev. I get `Error: read ECONNRESET` and the tunnel stops when trying to push to db from local or run drizzle studio.

**Comment by danielfyhr** [comment]
> 9. `sst refresh --stage prod` -> Maybe its updating the IPs? Not sure where they are in the state exactly -> Now the tunnel is 
> 10. Deployed prod again **And it works**

can confirm doing 9 and 10 fixed it for me as well 🚀 

note: before i did 9, i removed `.sst` folder, but im not sure if that's related

**Comment by jescalan** [comment]
I had this same issue and running `sst refresh` resolved it for me. Glad I found this thread, this one had me hung up for quite a while.

**Comment by handlebauer** [comment]
i tried all kinds of different permutations. eventually it was just switching `nat` from `ec2` to `managed` (this causes a failed deployment that i never resolved) and then back again to `ec2` — and then it worked.

**Comment by valerarusu7** [comment]
same issue

**Comment by acamaral** [comment]
Same here, and only restarting my Mac it worked.

**Comment by not-manu** [comment]
Here's how I fixed the issue without having to restart my laptop. I'm using **SST 3.14.11**

`vpc.ts`
```ts
export const vpc = new sst.aws.Vpc("MyVpc", {
  bastion: true,
  nat: "ec2",
});

```

`api.ts`
```ts
import { vpc } from "./vpc";
import { redis } from "./redis";

const api = new sst.aws.ApiGatewayV2("MyApi", {
  link: [redis],
  transform: {
    route: {
      handler: {
        vpc,
      }
    }
  }
});

api.route("$default", "packages/functions/src/api.handler");
```

1. First, I run `sst dev`
2. I navigate to the **Tunnel** process in the sidebar and press `x` to exit it
3. I open a new terminal window and open the tunnel manually by running `npx sst tunnel --print-logs`

I have no idea why this works, but I'm glad it does.

**Comment by gkpln3** [comment]
I have the same issue only when running with `--stage production`, `sst refresh` or restarting my mac did not solve it.
Seems like the tunnel is being made to the wrong IP.

**Comment by Aleksion** [comment]
I'm getting a mix of econnreset and econntimedout. Sometimes it works, but I cannot repeatedly figure out what and why. This is a pretty big blocker for our team since we cannot reliably connect to our databases.

**Comment by Aleksion** [comment]
I've noticed that it works if I turn on proxy - that breaks Zero though so running it with proxy isn't an option.

But maybe it is a clue

**Comment by jescalan** [comment]
Ah unfortunately while sst refresh fixed local env for me production is broken when i try to tunnel to it as @gkpln3 mentioned and refresh was unable to fix that one 😭

EDIT: Never mind, had to run refresh then deploy to production and it worked again 😖

**Comment by thdxr** [comment]
in v3.14.29 the tunnel command prints out the host ip it's connected to

if this does NOT match what you are seeing in aws console can you share `sst export --stage=<stage-vpc-is-in>`

**Comment by gkpln3** [comment]
After checking the `sst export` output, it looks like the tunnel is using the same IP shown in the bastion host’s `publicIp` field. However, the actual public IP is the one linked to the Elastic IP (eipalloc).

**Comment by gkpln3** [comment]
I think I traced the issue:
in `platform/src/components/aws/vpc.ts`
```ts
function registerOutputs() {
  self.registerOutputs({
    _tunnel: all([
      self.bastionInstance,
      self.privateKeyValue,
      self._privateSubnets,
      self._publicSubnets,
    ]).apply(
      ([bastion, privateKeyValue, privateSubnets, publicSubnets]) => {
        if (!bastion) return;
        return {
          ip: bastion.publicIp,
          username: "ec2-user",
          privateKey: privateKeyValue!,
          subnets: [...privateSubnets, ...publicSubnets].map(
            (s) => s.cidrBlock,
          ),
        };
      },
    ),
  });
}
```
Not sure, but I think the issue is that the `_tunnel` object is using the bastion.publicIp instead of the `eipalloc`.

**Comment by gkpln3** [comment]
I've been able to fix the issue, see #5820.

**Comment by joaquimserafim** [comment]
I was facing the same issue using SST 3.16.0. After downgrading to 3.9.39 (an earlier version that was working for me), I can now see the tunnel picking up the correct IP, I guess something change between versions.

![Image](https://github.com/user-attachments/assets/4084466c-6e72-4c90-a124-ebe04be39e1f)

**Comment by liyincode** [comment]
Hello, I just started using SST. However, I only successfully used the tunnel once. The scenario was that after updating the Mac system version and restarting the system, the unexpectedly worked.

But shortly after that, it stopped working properly again because the remote IP of the tunnel SSH was incorrect. I didn't find this bastion machine IP in my AWS console. 

This problem has been bothering me for a long time because I can't access the table structure of the remote RDS database.

**Comment by corybill** [comment]
I keep running into this problem. Doing this will fix it consistently.


First, you need to make sure you don't have any other sst running. I have found that I need to run this a lot.
```
ps aux | grep sst | awk '{print $2}' | xargs kill -9
```

Next, we need to remove the local config so we can reset it.
```
rm -rf .sst/platform
rm -rf .sst/pulumi
```

Then we can reset our local config by running another deploy.
```
sst deploy --stage <stage_name>
```

You can verify this issue by running the following command. You'll see the host IP being used in the logs. Then go to AWS Console and look for the EC2 instance with the tag sst:is-bastion = true. You'll see the public IP doesn't match the IP being used for the tunnel. Running the above commands seems to force a refresh.

```
npx sst tunnel --stage <stage_name> --print-logs
```

Note that this might be the same thing as running `refresh` and then `deploy` to your stage. You can try that first. The key is that you have to redeploy.

**Comment by eugene-pipelaunch** [comment]
|  Error       MyVpc sst:aws:Vpc → MyVpcNatGateway1 aws:ec2:NatGateway
sdk-v2/provider2.go:515: sdk.helper_schema: waiting for EC2 NAT Gateway (nat-00444864a646a1bcd) create: unexpected state 'failed', wanted target 'available'. last error: Resource.AlreadyAssociated: Elastic IP address [eipalloc-0408dceff836b3c13] is already associated: provider=aws@6.66.2
|  Error       MyVpc sst:aws:Vpc → MyVpcNatGateway2 aws:ec2:NatGateway
sdk-v2/provider2.go:515: sdk.helper_schema: waiting for EC2 NAT Gateway (nat-0fc36f0dae62bcbf9) create: unexpected state 'failed', wanted target 'available'. last error: Resource.AlreadyAssociated: Elastic IP address [eipalloc-066ebd043ce284d43] is already associated: provider=aws@6.66.2

✕  Failed    

MyVpc sst:aws:Vpc → MyVpcNatGateway1 aws:ec2:NatGateway
sdk-v2/provider2.go:515: sdk.helper_schema: waiting for EC2 NAT Gateway (nat-00444864a646a1bcd) create: unexpected state 'failed', wanted target 'available'. last error: Resource.AlreadyAssociated: Elastic IP address [eipalloc-0408dceff836b3c13] is already associated: provider=aws@6.66.2

MyVpc sst:aws:Vpc → MyVpcNatGateway2 aws:ec2:NatGateway
sdk-v2/provider2.go:515: sdk.helper_schema: waiting for EC2 NAT Gateway (nat-0fc36f0dae62bcbf9) create: unexpected state 'failed', wanted target 'available'. last error: Resource.AlreadyAssociated: Elastic IP address [eipalloc-066ebd043ce284d43] is already associated: provider=aws@6.66.2

**Comment by eugene-pipelaunch** [comment]
Let's try removing and readding again

**Comment by antonigiske** [comment]
> > 9. `sst refresh --stage prod` -> Maybe its updating the IPs? Not sure where they are in the state exactly -> Now the tunnel is
> > 10. Deployed prod again **And it works**
> 
> can confirm doing 9 and 10 fixed it for me as well 🚀
> 
> note: before i did 9, i removed `.sst` folder, but im not sure if that's related

Can confirm this works for me. I have bastion and ec2. I deleted .sst/, refreshes production and deployed to production. When I started the tunnel the IP is correct.

**Comment by pauljasperdev** [comment]
Tried updating from `3.10.7` to `3.17.10` today. No luck. Had the same issue again so I went back to `3.10.7`

**Comment by ghardin1314** [comment]
Just deployed a new VPC for a new project and running into this issue again. The only place in my state file showing the IP address the tunnel is trying to connect to is `_tunnel` output from the VPC. I think @gkpln3 might have the right fix here. Hopefully the team can merge shortly

**Comment by john-rtr** [comment]
Had the exact same problem.
Updating the vpc with nat config > deploying > removing the nat config > deploying worked

**Comment by pauljasperdev** [comment]
> I've been able to fix the issue, see [#5820](https://github.com/sst/sst/pull/5820).

~~works for me also.~~

~~I rebased @gkpln3's branch with the current and followed build steps for CLI. I use the executable with current SDK `3.17.10`~~

EDIT: does NOT fix it for me. Apprently, I just had a lucky deploy that time.

**Comment by maxandron** [comment]
> > > 9. `sst refresh --stage prod` -> Maybe its updating the IPs? Not sure where they are in the state exactly -> Now the tunnel is
> > > 10. Deployed prod again **And it works**
> > 
> > 
> > can confirm doing 9 and 10 fixed it for me as well 🚀
> > note: before i did 9, i removed `.sst` folder, but im not sure if that's related
> 
> Can confirm this works for me. I have bastion and ec2. I deleted .sst/, refreshes production and deployed to production. When I started the tunnel the IP is correct.

Doing sst refresh followed by sst deploy fixed my tunnel as well

For context on why it happened for me (to help you with debugging the issue): I used to have the VPC set to `bastion: true` but `nat` was undefined - and the tunnel worked well
I then changed to `nat: ec2`, which presumably removed the previous bastion instance and created a new one with a different IP - this is when the tunnel stopped working.

I'm running sst version 3.17.10

**Comment by maxscn** [comment]
> > > > 9. `sst refresh --stage prod` -> Maybe its updating the IPs? Not sure where they are in the state exactly -> Now the tunnel is
> > > > 10. Deployed prod again **And it works**
> > > 
> > > 
> > > can confirm doing 9 and 10 fixed it for me as well 🚀
> > > note: before i did 9, i removed `.sst` folder, but im not sure if that's related
> > 
> > 
> > Can confirm this works for me. I have bastion and ec2. I deleted .sst/, refreshes production and deployed to production. When I started the tunnel the IP is correct.
> 
> Doing sst refresh followed by sst deploy fixed my tunnel as well
> 
> For context on why it happened for me (to help you with debugging the issue): I used to have the VPC set to `bastion: true` but `nat` was undefined - and the tunnel worked well I then changed to `nat: ec2`, which presumably removed the previous bastion instance and created a new one with a different IP - this is when the tunnel stopped working.
> 
> I'm running sst version 3.17.10

I did something similar to do this and can confirm that the tunnel is not working right now at least. Not sure if it worked before. 

Can also confirm that refreshing and redeploying helped.

**Comment by handlebauer** [comment]
Confirmed this is still happening on `3.14.11`

**Comment by mtorcutt** [comment]
I'm having the same issue in 3.17.13. I've tried `sst refresh` and deleting `.sst` with no luck.

Edit: I got this working. Not sure exactly what did it but I had another project in the same account with `"VPC"` as the resource name. I removed that entire project/VPC, refreshed, and it started working.

**Comment by nl0243** [comment]
What worked for me was:
1. set nat from "ec2" to "managed"
2. sst refresh --stage <my_stage>
3. sst deploy --stage <my_stage> => fails
4. set nat back to "ec2"
5. sst deploy --stage <my_stage> => works

**Comment by pauljasperdev** [comment]
@jayair was anybody on the team able to recreate this? Not being able to upgrade becomes a real issue as volnurabilities are being detected in the sst dependencies.

**Comment by RandyLef1** [comment]
> What worked for me was:
> 
> 1. set nat from "ec2" to "managed"
> 2. sst refresh --stage <my_stage>
> 3. sst deploy --stage <my_stage> => fails
> 4. set nat back to  "ec2"
> 5. sst deploy --stage <my_stage> => works

This worked for me too @nl0243

**Comment by AlbertoV5** [comment]
I have had this issue on and off, fixes have been: updating, redeploying, restarting the mac, etc, all mentioned here. 

I just came across it again and was being able to revert in local dev by removing the last resource I created right before the Tunnel broke (removing import from sst config), re-running `bun sst dev` and the Tunnel comes back. Then I re-import the resource to keep working with it 🤷🏻 . The resource is a `sst.x.DevCommand`.

The tunnel breaks again after a while, may be related with running other sst processes, but can be fixed by doing the thing again. Restarting the mac didn't fix it this time, just the resource removal thing does, haven't tested redeploy, etc yet. MacOS 15.7.1 and sst 3.17.8

**Comment by damidina** [comment]
> I have had this issue on and off, fixes have been: updating, redeploying, restarting the mac, etc, all mentioned here.
> 
> I just came across it again and was being able to revert in local dev by removing the last resource I created right before the Tunnel broke (removing import from sst config), re-running `bun sst dev` and the Tunnel comes back. Then I re-import the resource to keep working with it 🤷🏻 . The resource is a `sst.x.DevCommand`.
> 
> The tunnel breaks again after a while, may be related with running other sst processes, but can be fixed by doing the thing again. Restarting the mac didn't fix it this time, just the resource removal thing does, haven't tested redeploy, etc yet. MacOS 15.7.1 and sst 3.17.8

Seems tedious

**Comment by smith558** [comment]
Has this been resolved? @andrewcoelho @pauljasperdev

**Comment by pauljasperdev** [comment]
> Has this been resolved? [@andrewcoelho](https://github.com/andrewcoelho) [@pauljasperdev](https://github.com/pauljasperdev)

I did not attempt to upgrade lately. Were there changes that should resolve the issue?

**Comment by danielsharvey** [comment]
I think this has been addressed by https://github.com/anomalyco/sst/pull/5820 though note https://github.com/anomalyco/sst/issues/6309.

**Comment by juxuanu** [comment]
I also have tunnel not working.
```sh
sudo sst tunnel install # works
sst tunnel # no tunnels found for stage
```
I see it's using 10.0.0.0 range, which is used as well for my LAN at home (my current PC IP is 10.0.0.109). I guess this conflicts as well?

Anyway it just doesn't work.

**Comment by cgilly2fast** [comment]
> I tried a _ton_ of things - upgrading, downgrading, re-deploying, managed/nat, etc. None worked, then I restarted my Mac and it worked 🤷

Restarting my computer worked for me

**Comment by adamcorina** [comment]
I was using `sst tunnel` to connect my local app to a Postgres (Aurora) database in AWS (e.g. `my-db.cluster-abc123xyz.us-east-1.rds.amazonaws.com`).

After physically changing location (different Wi-Fi / different router), the connection started continuously failing with:

```
errno: -3008,
code: 'ENOTFOUND',
syscall: 'getaddrinfo',
hostname: my-db.cluster-abc123xyz.us-east-1.rds.amazonaws.com
```


At the same time, sst tunnel would not exit with an error - it stayed pending (“Waiting for connections…”).


This turned out to be a router DNS issue, not an SST or AWS networking problem. The new router’s built-in DNS forwarder was failing to properly resolve the Aurora cluster hostname (CNAME chain), returning empty DNS answers. Because the hostname could not be resolved reliably, the app failed with ENOTFOUND, which made it look like an SST/tunnel issue.

I solved it by overriding the system DNS to use a proper recursive resolver (e.g. 1.1.1.1, 8.8.8.8) instead of the router DNS. After switching DNS and flushing cache, the Postgres connection via sst tunnel worked normally again. 

How to do it on a macbook:

Test that your local machine can't resolve the domain:

```
dig +short my-db.cluster-abc123xyz.us-east-1.rds.amazonaws.com
```

1. Open System Settings
2. Click Network
3. Click Wi-Fi
4. Click Details
5. Click DNS in the sidebar
6. Under DNS Servers, you’ll likely see: 192.168.1.1
7. Click the – (minus) button to remove it
8. Click + and add:
- 1.1.1.1 (DNS resolver operated by Cloudflare)
- 8.8.8.8 (DNS resolver operated by Google)
9. Click apply
10. Open Terminal and run
```
sudo dscacheutil -flushcache
sudo killall -HUP mDNSResponder
```


Verify it worked:
```
dig +short my-db.cluster-abc123xyz.us-east-1.rds.amazonaws.com
```
